games/urls.py
from django.urls import path

app_name = 'games'
urlpatterns = []

pages/urls.py
from django.urls import path
from . import views

from .views import AboutUsView, ContactForm, HomePageView

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('contact/', ContactForm.as_view(), name='contact'),
]

playtolearn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),

    # Local Apps
    path('', include('pages.urls')),
    path('account/', include('users.urls')),
    path('games/', include('games.urls')),
]

users/urls.py
from django.urls import path

from .views import CustomPasswordChangeView, MyAccountPageView

urlpatterns = [
    path(
        "password/change/", CustomPasswordChangeView.as_view(),
        name="account_change_password"
    ),
    path('my-account/', MyAccountPageView.as_view(), name='my-account'),
]

games/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.db import models
from django.urls import reverse

def validate_avatar(value):
    w, h = get_image_dimensions(value)
    if w > 200 or h > 200:
        raise ValidationError('Avatar must be no bigger than 200x200 pixels.')

class CustomUser(AbstractUser):
    dob = models.DateField(
        verbose_name="Date of Birth", null=True, blank=True
    )
    
    def get_absolute_url(self):
        return reverse('my-account')

pages/forms.py
from django import forms

class ContactForm(forms.Form):
    your_name = forms.CharField(max_length=100)
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=100, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

users/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm


BIRTH_YEAR_CHOICES = range(1915, datetime.now().year)

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=50, required=False)
    last_name = forms.CharField(max_length=50, required=False)

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

class CustomUserChangeForm(UserChangeForm):
    password = None
    
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'first_name', 'last_name', 'dob')
        widgets = {
            'dob': forms.SelectDateWidget(
                attrs={
                    'style': 'width: 31%; display: inline-block; margin: 0 1%'
                },
                years = BIRTH_YEAR_CHOICES
            )
        }

games/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.contrib import messages
from .forms import ContactForm
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView


# Create your views here.
class AboutUsView(TemplateView):
    template_name = 'pages/about_us.html'

    def get(self, request, *args, **kwargs):
        messages.debug(request, 'Debug message.')
        messages.info(request, 'Info message.')
        messages.success(request, 'Success message.')
        messages.warning(request, 'Warning message.')
        messages.error(request, 'Error message.')
        return super().get(request, args, kwargs)


class ContactForm(FormView):
    template_name = 'pages/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('pages:thanks.html')


class HomePageView(TemplateView):
    template_name = 'pages/home.html'

users/views.py
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from allauth.account.views import PasswordChangeView

from .forms import CustomUserChangeForm

class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('my-account')

class MyAccountPageView(UpdateView):
    model = get_user_model()
    form_class = CustomUserChangeForm
    success_message = 'Update Successful'
    template_name = 'account/my_account.html'

    def get_object(self):
        return self.request.user

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<script src="https://kit.fontawesome.com/b48ff8a378.js" crossorigin="anonymous"></script>
<title>{% block title %}{% endblock %} | Play to Learn</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" id="topNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pages:homepage' %}">LTP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'pages:homepage' %}">Home</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
            </li>
            {% else %}
            <li class="nav-item dropdown" id="navDropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" 
              aria-haspopup="true" aria-expanded="false">Games</a>
              <ul class="dropdown-menu" aria-labelledby="navDropdown">
                <li>
                  <a class="dropdown-item" href="/anagramhunt">Anagram Hunt</a>
                </li>
                <li>
                  <a class="dropdown-item" href="/mathfacts">Math Facts Practice</a>
                </li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
              role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'my-account' %}">My Account</a>
              <a class="dropdown-item" href="#">My Scores</a>
              <div class="dropdown-divider"></div>
              <form method="post" action="{% url 'account_logout' %}">
                {% csrf_token %}
                <button class="btn dropdown-item">Log out</button>
              </form>
            </div>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:about-us' %}">About</a>
          </li>
        </ul>
        </div>
      </div>
    </nav>
</header>
  {% if messages %}
    <ul>
      {% for message in messages %}
      <div class="alert message{{ message.tags }} alert-dismissible" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="close" data-dismiss="alert"
            aria-label="Close">
            <i class="fas fa-window-close"></i>
          </button>
        </div>
      {% endfor %}
    </ul>
  {% endif %}
{% block main %}

{% endblock %}
<footer class="fixed-bottom bg-light row">
    <div class="col">
      <div class="float-right m-1 mr-2">Copyright &copy; 2020 Play to Learn.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:contact' %}">Contact</a>
          </li>
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="/admin/">Admin</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </nav>
</footer>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

templates/pages/about_us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block main %}
  <div class="mb-2">
    <div class="jumbotron">
      <div class="about-title">About Us</div>
      <div class="about-title-caption">
        Our goal is to make learning more fun.
      </div>
    </div>
    <div class="w-75 m-auto">
      <div class="row align-items-center m-auto"></div>
      <br />
      <div class="row align-items-center justify-content-between">
        <div class="display-4 col-md-3 col-sm-12 p-1 about-body-title">
          About us:
        </div>
        <div class="col-md-8 col-sm-12 p-1 about-body-caption">
          Our team was put together with one common goal in mind: To make as
          many people as we can WANT to learn things. We believe that we are
          held back as a species because there is a lack of excitement and
          innovation when it comes to education.
        </div>
      </div>
      <hr />
      <br />
      <div class="row align-items-center justify-content-between">
        <div class="col-sm-12 display-4 d-block d-md-none about-body-title">
          Our Mission:
        </div>
        <div class="col-md-8 col-sm-12 about-body-caption">
          Our team was put together with one common goal in mind: To make as
          many people as we can WANT to learn things. We believe that we are
          held back as a species because there is a lack of excitement and
          innovation when it comes to education.
        </div>
        <div class="col-3 display-4 d-none d-md-block about-body-title">
          :Our Mission
        </div>
      </div>
      <br />
      <hr />
      <br />
      <div class="row align-items-center justify-content-between">
        <div class="display-4 col-md-3 col-sm-12 p-1 about-body-title">
          Our Success:
        </div>
        <div class="col-md-8 col-sm-12 p-1 about-body-caption">
          We have had a tremendous amount of success across the country. So much
          success that I am too busy having success to actually spend the time
          to write a decent paragraph about the success that we have had.
        </div>
      </div>
    </div>
    <br />
  </div>
{% endblock %}

templates/pages/contact.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %}Contact Us{% endblock %}
{% block main %}

{% if submitted %}
<p class="success">Your message was submitted successfully. Thank you.</p>

{% else %}
  <div class="card border-primary m-auto mb-3" style="max-width: 30rem">
    <div class="card-header text-center">Contact us</div>
    <div class="card-body">
      <form method="post" class="m-auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="form-control btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
{% endif %}

{% endblock %}

templates/pages/home.html
{% extends "_base.html" %}

{% block title %}Home{% endblock %}
{% block main %}
<main class="m-4 pb-5">
  {% if messages %}
    <ul>
      {% for message in messages %}
      <div class="alert message{{ message.tags }} alert-dismissible" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="close" data-dismiss="alert"
            aria-label="Close">
            <i class="fas fa-window-close"></i>
          </button>
        </div>
      {% endfor %}
    </ul>
  {% endif %}
    <div class="home row align-items-center m-auto pb-5">
      <div class="bg-warning w-100">
        <div class="home-title text-center text-dark">
          Welcome to Play to Learn
        </div>
        <div class="home-title-caption lead text-center">
          your number one source for free online learning!
        </div>
      </div>
    <div
      id="myCarousel"
      class="carousel border-dark"
      data-ride="carousel"
      data-interval="10000"
    >
      <ol class="carousel-indicators carousel-indicator-important">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="carousel-darkening-overlay"></div>
          <img
            src="static/images/carouselImage1Cropped.jpg"
            id="firstCarouselImage"
            alt="First Slide"
            class="d-block w-100"
          />
          <div class="carousel-caption carousel-caption-important lead m-auto">
            "By far the easiest way to learn!"
          </div>
        </div>
        <div class="carousel-item">
          <div class="carousel-darkening-overlay"></div>
          <img
            src="static/images/carouselImage2Cropped.jpg"
            id="SecondCarouselImage"
            alt="Second Slide"
            class="d-block w-100"
          />
          <div class="carousel-caption carousel-caption-important lead m-auto">
            "These games make me want to learn!"
          </div>
        </div>
        <div class="carousel-item">
          <div class="carousel-darkening-overlay"></div>
          <img
            src="static/images/carouselImage3Cropped.jpg"
            id="thirdCarouselImage"
            alt="Third Slide"
            class="d-block w-100"
          />
          <div class="carousel-caption carousel-caption-important lead m-auto">
            "Easy to play on mobile or on desktop!"
          </div>
        </div>
        <a
          href="#myCarousel"
          class="carousel-control-prev"
          role="button"
          data-slide="prev"
        >
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a
          href="#myCarousel"
          class="carousel-control-next"
          role="button"
          data-slide="next"
        >
          <span class="carousel-control-next-icon"></span>
        </a>
      </div>
    </div>
    <div class="row pt-1 w-100 m-auto">
      <div class="col-sm-12 col-md-6 card text-center border-0">
        <img src="static/images/anagram.png" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-body-title">Anagram Hunt</h5>
          <p class="card-body-caption">
            In exchange for clicking the button below, you will be given a word.
            You will choose the length of the word. From that word, you will
            birth new words. At the end there will be a giant billboard that
            tells your how good (or bad) you did!
          </p>
        </div>
        <a href="/anagramhunt" class="btn btn-warning m-3">Play this one!</a>
      </div>
      <div class="col-sm-12 col-md-6 card text-center border-0">
        <img src="static/images/mathfacts.jpg" class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-body-title">Math Facts Practice</h5>
          <p class="card-body-caption">
            But if you were to click THIS button (look down) You will have 30
            seconds to rapidly come up with the answer to 10 extremely simple
            math equations. If you can master all 4 operations offered to you,
            you will be the recipient of the most bragging rights you have ever
            had to the right to. Ever. Oh and see a scoreboard.
          </p>
        </div>
        <a href="/mathfacts" class="btn btn-warning m-3">No, play this one!</a>
      </div>
    </div>
  </div>

</main>

{% endblock %}

templates/pages/thanks.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Check Your Email{% endblock %}

{% block main %}
<div class="card border-primary m-auto mb-3" style="max-width: 30rem">
  <div class="card-header text-center">Check Your Email</div>
  <div class="card-body">
    <p class="card-text text-center">
      Check your email for instructions on resetting your password.
    </p>
  </div>
</div>
{% endblock %}